In [1]:
import time
start_time=time.time()
import numpy as np
import matplotlib as plt
import pandas as pd
from apyori import apriori
import re

In [2]:
file1 = '/home/chanidu/Desktop/T10I4D100K.csv'
file2 ='/home/chanidu/Desktop/T40I10D100K.csv'
file3 ='/home/chanidu/Desktop/T10I4D100K.csv'

df  = pd.read_csv(file2,header= None)

df.shape

(100000, 62)

In [3]:
df.head(19)

,0,1,2,3,4,5,6,7,8,9,...,52,53,54,55,56,57,58,59,60,61
0,36,69,115,226,278.0,343.0,345.0,358.0,368.0,370.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8,51,55,73,78.0,117.0,140.0,175.0,187.0,229.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,53,55,98,159,192.0,322.0,332.0,402.0,412.0,413.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,48,203,205,227,279.0,294.0,320.0,335.0,359.0,414.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,58,69,73,82,120.0,146.0,166.0,178.0,217.0,220.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,10,18,75,120,185.0,194.0,205.0,206.0,321.0,339.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,38,175,243,329,371.0,378.0,385.0,440.0,450.0,541.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,20,31,35,38,71.0,73.0,98.0,102.0,120.0,127.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1,4,49,72,107.0,108.0,115.0,124.0,142.0,146.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,21,38,59,71,72.0,104.0,122.0,137.0,180.0,196.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,28,54,55,70,82.0,115.0,204.0,205.0,225.0,245.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,10,27,100,104,175.0,206.0,296.0,360.0,394.0,400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,16,51,54,55,69.0,100.0,171.0,179.0,182.0,183.0,...,975.0,982.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,38,39,43,45,129.0,136.0,174.0,194.0,203.0,241.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,70,120,122,143.0,183.0,205.0,229.0,272.0,274.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,43,45,67,73,90.0,111.0,112.0,118.0,142.0,154.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,25,26,32,107,112.0,161.0,163.0,217.0,243.0,276.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,51,97,105,110,115.0,145.0,183.0,187.0,204.0,205.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,8,31,46,73,93.0,118.0,132.0,141.0,196.0,259.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
num_records= len(df)
print(num_records)
df.shape

100000

(100000, 62)

In [ ]:
records = []
for i in range(0,1000):
    records.append([df.values[i,j] for j in range(0,62)])
print("done")

In [ ]:
start_time1=time.time()
association_rules = apriori(records,min_support= 0.015)
association_results= list(association_rules)

In [ ]:
print(len(association_results))

In [ ]:
print(association_results[0])

In [ ]:
stop_time=time.time()
Total = stop_time-start_time1
print(Total)